config/routes.rb
Rails.application.routes.draw do
  get 'categories/new'

  get 'categories/create'

  get 'categories/update'

  get 'categories/edit'

  get 'categories/destroy'

  get 'categories/index'

  get 'categories/show'

  get 'items/new'

  get 'items/create'

  get 'items/update'

  get 'items/edit'

  get 'items/destroy'

  get 'items/index'

  get 'items/show'

  get 'about/index'

  get 'about' => 'about#index'

  root 'items#index'

  resources :items
  resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @page_title = 'About us';
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
<div class="well">
  <h3>Contact Info</h3>
  <ul>
    <li>The Shop</li>
    <li>Address:Saarbrücken, Deutschland</li>
    <li>Phone   : 765757575</li>
    <li>Email   : xxxxx@xx.com</li>
  </ul>
</div>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<div id= "items-index">
  <div class="row">
   <div class="col-md-3 col-sm-3">
    <h3>Spinner</h3>
    <%= image_tag('imgs/img1.jpg') %>
    <%= link_to 'Read More' , item_path(1) , class: 'btn btn-primary' %>
   </div>
   <div class="col-md-3 col-sm-3">
     <h3>Spinner</h3>
     <%= image_tag('imgs/img2.jpg') %>
     <%= link_to 'Read More' , item_path(2) , class: 'btn btn-primary' %>
   </div>
   <div class="col-md-3 col-sm-3">
     <h3>Spinner</h3>
     <%= image_tag('imgs/img3.jpg') %>
     <%= link_to 'Read More' , item_path(3) , class: 'btn btn-primary' %>
   </div>
   <div class="col-md-3 col-sm-3">
     <h3>Spinner</h3>
     <%= image_tag('imgs/img4.jpg') %>
     <%= link_to 'Read More' , item_path(4) , class: 'btn btn-primary' %>
   </div>
 </div>
 <div class="row">
  <div class="col-md-3 col-sm-3">
   <h3>Spinner</h3>
   <%= image_tag('imgs/img5.jpg') %>
   <%= link_to 'Read More' , item_path(5) , class: 'btn btn-primary' %>
  </div>
  <div class="col-md-3 col-sm-3">
    <h3>Spinner</h3>
    <%= image_tag('imgs/img6.jpg') %>
    <%= link_to 'Read More' , item_path(6) , class: 'btn btn-primary' %>
  </div>
  <div class="col-md-3 col-sm-3">
    <h3>Spinner</h3>
    <%= image_tag('imgs/img7.jpg') %>
    <%= link_to 'Read More' , item_path(7) , class: 'btn btn-primary' %>
  </div>
  <div class="col-md-3 col-sm-3">
    <h3>Spinner</h3>
    <%= image_tag('imgs/img8.jpg') %>
    <%= link_to 'Read More' , item_path(8) , class: 'btn btn-primary' %>
  </div>
 </div>
</div>

app/views/items/new.html.erb
<h2>Add New Item</h2>

<%= form_for @item do |f| %>

    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, class:'form-control' %><br />
    </div>

    <div class="form-group">
      <%= f.label :category %><br />
      <%= f.text_field :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %><br />
    </div>

    <div class="form-group">
      <%= f.label :specifications %><br />
      <%= f.text_field :specifications, class:'form-control' %><br />
    </div>

    <div class="form-group">
      <%= f.label :descriptions %><br />
      <%= f.text_field :descriptions, class:'form-control' %><br />
    </div>

    <div class="form-group">
      <%= f.label :price %><br />
      <%= f.text_field :price, class:'form-control' %><br />
    </div>

    <div class="form-group">
      <%= f.label :buy %><br />
      <%= f.text_field :buy, class:'form-control' %><br />
    </div>

    <%= f.submit "Submit", class:'btn btn-primary' %>
    <%= link_to "Cancel", items_path, class:'btn btn-default' %>

<% end %>

app/views/items/show.html.erb
<div id="items-show">
  <h2>Spinner</h2>
  <div class="items-show-left">
    <%= image_tag('imgs/img1.jpg') %>
  </div>
  <div class="items-show-right">
    <h3>Item info</h3>
    <ul>

    </ul>
  </div>
</div>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title ? @page_title : 'Welcome' %> | The Store </title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
      </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller] == 'items' ? 'active' : '' %>"><%= link_to 'Home' , root_path %></li>
            <li class="<%= params[:controller] == 'about' ? 'active' : '' %>"><%= link_to 'About' , about_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">+ New <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'New Item' , new_item_path %></li>

         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <header>
      <div class="container">
        <h1>The Shop <small><%= @page_title ? @page_title : 'Welcome' %> </small><h1>
      </div>
    </header>

  <section>
      <div class="container">
        <div class="row">
          <div class="col-md-8">
              <%= yield %>
          </div>
          <div class="col-med-4">
          <%= render 'partials/sidebar' %>
          </div>

        </div>
      </div>
  </section>

  <footer>
    <div class="container">
      <p>Copyright &copy 2017, All Right Reserved</p>
    </div>
  </footer>
  </body>
</html>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'items' && params[:action] == 'index' || params[:action] == 'show' %>
  <div class="list-group">
    <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
    <a href="#" class="list-group-item">Morbi leo risus</a>
    <a href="#" class="list-group-item">Porta ac consectetur ac</a>
    <a href="#" class="list-group-item">Vestibulum at eros</a>
  </div>
<% end %>  